import 'dart:io';
import 'dart:convert';

// Semantic version - update this when releasing major/minor/patch versions
const String semanticVersion = '1.0.0';

void main() async {
  // Read current version
  final versionFile = File('version.json');
  
  int buildNumber = 1;
  
  if (await versionFile.exists()) {
    final content = await versionFile.readAsString();
    final json = jsonDecode(content) as Map<String, dynamic>;
    buildNumber = (json['buildNumber'] as int? ?? 0) + 1;
  }
  
  // Write incremented version
  final newVersion = {
    'buildNumber': buildNumber,
  };
  
  await versionFile.writeAsString(
    const JsonEncoder.withIndent('  ').convert(newVersion) + '\n',
  );
  
  // Generate Dart file
  // Note: This generated file is intentionally tracked in Git (not in .gitignore)
  // because the version needs to persist across builds and be available immediately
  // after checkout. It serves as the source of truth for the current build number.
  final generatedFile = File('lib/generated/version.dart');
  await generatedFile.parent.create(recursive: true);
  
  final dartContent = '''
// GENERATED FILE - DO NOT EDIT
// This file is auto-generated by scripts/increment_version.dart

class AppVersion {
  static const int buildNumber = $buildNumber;
  static const String version = '$semanticVersion+$buildNumber';
}
''';
  
  await generatedFile.writeAsString(dartContent);
  
  print('Version incremented to build $buildNumber');
  print('Generated lib/generated/version.dart');
}
